name: Create Release Draft
on: workflow_dispatch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: "master"
      - run: git fetch --prune --unshallow

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: |
          npm i

      - name: Prepare Release Changelog
        id: changelog
        run: |
          npm run prepare:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/setup-env

      - name: Build Packages
        run: |
          stack test --fast --bench --no-run-benchmarks --haddock --no-haddock-deps

      - name: Prepare Artifacts
        run: |
          stack sdist

      - name: Commit changes
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git add .
          git status
          git commit -m "release-${{ steps.changelog.outputs.version }}"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/morpheusgraphql/morpheus-graphql.git HEAD:release-${{ steps.changelog.outputs.version }}

      - name: Create Release Draft
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.version }}
          release_name: ${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.body }}
          draft: true
